title: Catalin Codes
description: >- 

  Transforming ideas into code. 
  
  Follow my journey on personal and professional growth through the lens of a .NET developer. 
  
  Portfolio coming soon.
  
domain: catalin.codes
baseurl: ""
url: "https://catalin.codes"
twitter_username: catalincodes
github_username:  catalincodes

defaults:
  - scope:
      path: "" # This means "all files"
      type: "posts" # This targets posts
    values:
      image: "assets/og-image.png"
  - scope:
      path: ""
      type: "pages" # This targets general pages like index.md, about.md, etc.
    values:
      image: "assets/og-image.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag